# CLIP parameters
dataset-type: csv
aro-datasets-path: /equilibrium/datasets/aro_datasets
train-data: ./datasets/train2017.csv
val-data: ./datasets/val2017.csv
warmup: 50
batch-size: 128 
lr: 1e-6
wd: 0.1
epochs: 5
workers: 8
model: ViT-B-32
pretrained: openai
polytope: False
report-to: wandb
coca-contrastive-loss-weight: 0
coca-caption-loss-weight: 1
log-every-n-steps: 100
wandb-project-name: CLIP
lr-scheduler: cosine


